import React, { useState, useId } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Calendar, Clock, User, Sparkles, Check, ChevronRight, ChevronLeft, Trash2, ShieldCheck } from 'lucide-react';
import { SERVICE_CATEGORIES, STYLISTS } from '../data';
import { ServiceItem, Stylist, Appointment } from '../types';
import { supabase } from '../lib/supabaseClient';

interface BookingFormProps {
  onBookingSuccess: (appointment: Appointment) => void;
  existingBookings: Appointment[];
  onCancelBooking: (id: string) => void;
}

export default function BookingForm({ onBookingSuccess, existingBookings, onCancelBooking }: BookingFormProps) {
  const [step, setStep] = useState(1);
  const [selectedCategory, setSelectedCategory] = useState(SERVICE_CATEGORIES[0].id);
  const [selectedService, setSelectedService] = useState<ServiceItem | null>(null);
  const [selectedStylist, setSelectedStylist] = useState<Stylist | null>(null);
  const [selectedDate, setSelectedDate] = useState('');
  const [selectedTime, setSelectedTime] = useState('');
  const [clientName, setClientName] = useState('');
  const [clientPhone, setClientPhone] = useState('');
  const [clientEmail, setClientEmail] = useState('');
  const [successBooking, setSuccessBooking] = useState<Appointment | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const nameInputId = useId();
  const phoneInputId = useId();
  const emailInputId = useId();

  // Next 7 days for quick selection
  const getNextDays = () => {
    const days = [];
    const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    for (let i = 0; i < 7; i++) {
      const date = new Date();
      date.setDate(date.getDate() + i);
      days.push({
        formatted: date.toISOString().split('T')[0],
        dayName: weekdays[date.getDay()],
        dayNum: date.getDate(),
        month: date.toLocaleString('default', { month: 'short' }),
      });
    }
    return days;
  };

  const nextDays = getNextDays();

  // Premium time slots
  const timeSlots = [
    '09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', 
    '01:00 PM', '02:00 PM', '03:00 PM', '04:00 PM', 
    '05:00 PM', '06:00 PM', '07:00 PM', '08:00 PM'
  ];

  const handleNextStep = () => {
    if (step === 1 && !selectedService) return;
    if (step === 2 && !selectedStylist) return;
    if (step === 3 && (!selectedDate || !selectedTime)) return;
    setStep((prev) => prev + 1);
  };

  const handlePrevStep = () => {
    setStep((prev) => prev - 1);
  };

  const handleServiceSelect = (service: ServiceItem) => {
    setSelectedService(service);
  };

  const handleStylistSelect = (stylist: Stylist) => {
    setSelectedStylist(stylist);
  };

  const handleBookingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validation: Ensure all required fields are filled
    if (!clientName || !clientPhone || !selectedService || !selectedDate || !selectedTime) {
      setError('Please fill in all required fields.');
      return;
    }

    setIsLoading(true);
    setError(null);

    // Prepare data for Supabase table 'appointments'
    // Table columns: id (auto), client_name, client_phone, service_name, date, time, created_at (auto)
    const appointmentData = {
      client_name: clientName,               // ✅ Exact column name
      client_phone: clientPhone,             // ✅ Exact column name
      service_name: selectedService.name,    // ✅ Exact column name
      date: selectedDate,                    // ✅ Format: YYYY-MM-DD (from date picker)
      time: selectedTime,                    // ✅ Format: HH:MM AM/PM (from timeSlots)
      // Note: id and created_at are auto-generated by Supabase - do NOT include
    };

    console.log('\n' + '='.repeat(60));
    console.log('📤 APPOINTMENT SUBMISSION');
    console.log('='.repeat(60));
    console.log('Data being sent to Supabase:', appointmentData);
    console.log('Table: appointments');
    console.log('='.repeat(60));

    try {
      // Insert appointment data into Supabase
      const { data, error } = await supabase
        .from('appointments')
        .insert([appointmentData]);

      // Check for errors
      if (error) {
        console.error('❌ Supabase Error Details:');
        console.error('Message:', error.message);
        console.error('Code:', error.code);
        console.error('Details:', error.details);
        console.error('Hint:', error.hint);
        throw error;
      }

      // Success: Create appointment object for local state
      const newAppointment: Appointment = {
        id: data?.[0]?.id || `app-${Date.now()}`,
        serviceId: selectedService.id,
        serviceName: selectedService.name,
        stylistId: selectedStylist?.id || '',
        stylistName: selectedStylist?.name || '',
        date: selectedDate,
        time: selectedTime,
        clientName,
        clientPhone,
        clientEmail,
        createdAt: data?.[0]?.created_at || new Date().toISOString(),
      };

      console.log('✅ Appointment saved successfully:', data);
      console.log('Local state updated with:', newAppointment);

      // Update component state
      onBookingSuccess(newAppointment);
      setSuccessBooking(newAppointment);
      setStep(5); // Show success screen

    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to save appointment. Please try again.';
      
      console.error('❌ Failed to insert appointment:');
      console.error('Error:', errorMessage);
      console.error('Full error object:', err);

      setError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const resetForm = () => {
    setStep(1);
    setSelectedService(null);
    setSelectedStylist(null);
    setSelectedDate('');
    setSelectedTime('');
    setClientName('');
    setClientPhone('');
    setClientEmail('');
    setSuccessBooking(null);
    setError(null);
  };

  const currentCategoryObj = SERVICE_CATEGORIES.find((cat) => cat.id === selectedCategory);

  return (
    <div className="w-full grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
      {/* Booking Form Interface */}
      <div className="lg:col-span-8 bg-[#0d0d0d] border border-white/5 rounded-none p-6 md:p-8 relative overflow-hidden studio-light">
        <div className="flex justify-between items-center mb-8 border-b border-white/5 pb-4">
          <div>
            <h3 className="font-display text-xl uppercase tracking-wider text-white font-light">Book Luxury Session</h3>
            <p className="text-xs text-white/50 font-sans font-light mt-1">Experience precision grooming & luxury wellness</p>
          </div>
          {step <= 4 && (
            <div className="text-xs font-mono bg-primary/10 text-primary border border-primary/20 px-3 py-1 rounded-none uppercase tracking-widest">
              Step {step} of 4
            </div>
          )}
        </div>

        {/* Form Steps */}
        <AnimatePresence mode="wait">
          {step === 1 && (
            <motion.div
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              className="space-y-6"
            >
              <div>
                <label className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-3">
                  1. Select Category
                </label>
                <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
                  {SERVICE_CATEGORIES.map((cat) => (
                    <button
                      key={cat.id}
                      onClick={() => {
                        setSelectedCategory(cat.id);
                        setSelectedService(null);
                      }}
                      className={`py-3 px-2 rounded-none text-center border transition-all text-xs uppercase font-mono tracking-wider flex flex-col items-center justify-center gap-1 ${
                        selectedCategory === cat.id
                          ? 'bg-primary text-on-primary border-primary'
                          : 'bg-[#050505] hover:bg-[#121212] border-white/5 text-white/50 hover:text-white'
                      }`}
                    >
                      <span>{cat.title.split(' ')[0]}</span>
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <div className="flex justify-between items-center mb-3">
                  <label className="block text-xs font-mono uppercase tracking-widest text-white/50">
                    2. Choose Elite Service
                  </label>
                  <span className="text-[10px] uppercase font-mono text-primary animate-pulse">{currentCategoryObj?.tag}</span>
                </div>
                <div className="space-y-2 max-h-[300px] overflow-y-auto pr-1">
                  {currentCategoryObj?.items.map((service) => {
                    const isSelected = selectedService?.id === service.id;
                    return (
                      <button
                        key={service.id}
                        onClick={() => handleServiceSelect(service)}
                        className={`w-full p-4 rounded-none text-left border transition-all flex justify-between items-center group relative overflow-hidden ${
                          isSelected
                            ? 'bg-primary/10 border-primary text-white'
                            : 'bg-[#050505] hover:bg-[#121212] border-white/5 text-white/50 hover:text-white'
                        }`}
                      >
                        {isSelected && (
                          <div className="absolute top-0 left-0 w-1 h-full bg-primary" />
                        )}
                        <div className="pr-4">
                          <h4 className="font-display text-sm uppercase tracking-wider text-white group-hover:text-primary transition-colors">
                            {service.name}
                          </h4>
                          <p className="text-xs font-sans text-white/50 mt-1 line-clamp-1 font-light">
                            {service.description}
                          </p>
                        </div>
                        <div className="text-right shrink-0">
                          <span className="font-mono text-sm font-bold text-primary block">{service.price}</span>
                          <span className="text-[10px] uppercase font-mono text-white/40">Select</span>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="pt-4 flex justify-end">
                <button
                  onClick={handleNextStep}
                  disabled={!selectedService}
                  className={`flex items-center gap-2 px-6 py-3 rounded-none font-mono text-xs uppercase tracking-widest font-bold transition-all ${
                    selectedService
                      ? 'bg-primary text-on-primary hover:opacity-95'
                      : 'bg-white/5 text-white/30 cursor-not-allowed'
                  }`}
                >
                  Select Artist <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </motion.div>
          )}

          {step === 2 && (
            <motion.div
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              className="space-y-6"
            >
              <div>
                <label className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-4">
                  Choose Your Styling Professional
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {STYLISTS.map((stylist) => {
                    const isSelected = selectedStylist?.id === stylist.id;
                    return (
                      <button
                        key={stylist.id}
                        onClick={() => handleStylistSelect(stylist)}
                        className={`p-4 rounded-none border text-left flex gap-4 transition-all relative overflow-hidden group ${
                          isSelected
                            ? 'bg-primary/10 border-primary text-white'
                            : 'bg-[#050505] hover:bg-[#121212] border-white/5 text-white/50 hover:text-white'
                        }`}
                      >
                        {isSelected && (
                          <div className="absolute top-0 left-0 w-1 h-full bg-primary" />
                        )}
                        <img
                          src={stylist.image}
                          alt={stylist.name}
                          className="w-16 h-16 rounded-none object-cover border border-white/10"
                        />
                        <div>
                          <h4 className="font-display text-sm uppercase tracking-wider text-white group-hover:text-primary transition-colors font-light">
                            {stylist.name}
                          </h4>
                          <p className="text-xs text-primary font-mono mt-1">{stylist.role}</p>
                          <p className="text-[10px] text-white/40 font-sans mt-2 font-light">
                            Specialty: {stylist.specialty}
                          </p>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="pt-4 flex justify-between">
                <button
                  onClick={handlePrevStep}
                  className="flex items-center gap-2 px-5 py-3 border border-white/5 hover:bg-[#121212] rounded-none font-mono text-xs uppercase tracking-widest text-white/50 hover:text-white transition-all"
                >
                  <ChevronLeft className="w-4 h-4" /> Back
                </button>
                <button
                  onClick={handleNextStep}
                  disabled={!selectedStylist}
                  className={`flex items-center gap-2 px-6 py-3 rounded-none font-mono text-xs uppercase tracking-widest font-bold transition-all ${
                    selectedStylist
                      ? 'bg-primary text-on-primary hover:opacity-95'
                      : 'bg-white/5 text-white/30 cursor-not-allowed'
                  }`}
                >
                  Select Schedule <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </motion.div>
          )}

          {step === 3 && (
            <motion.div
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
              className="space-y-6"
            >
              <div>
                <label className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-4">
                  Choose Appointment Date
                </label>
                <div className="grid grid-cols-4 sm:grid-cols-7 gap-2">
                  {nextDays.map((day) => {
                    const isSelected = selectedDate === day.formatted;
                    return (
                      <button
                        key={day.formatted}
                        onClick={() => setSelectedDate(day.formatted)}
                        className={`p-3 rounded-none text-center border transition-all flex flex-col items-center justify-center ${
                          isSelected
                            ? 'bg-primary text-on-primary border-primary'
                            : 'bg-[#050505] hover:bg-[#121212] border-white/5 text-white/50 hover:text-white'
                        }`}
                      >
                        <span className="text-[10px] font-mono uppercase opacity-75">{day.dayName}</span>
                        <span className="text-lg font-bold font-display mt-1">{day.dayNum}</span>
                        <span className="text-[10px] font-mono uppercase opacity-75">{day.month}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              <div>
                <label className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-4">
                  Available Time Slots
                </label>
                <div className="grid grid-cols-3 sm:grid-cols-4 gap-2">
                  {timeSlots.map((slot) => {
                    const isSelected = selectedTime === slot;
                    return (
                      <button
                        key={slot}
                        onClick={() => setSelectedTime(slot)}
                        className={`py-3 px-2 rounded-none text-center border transition-all font-mono text-xs ${
                          isSelected
                            ? 'bg-primary text-on-primary border-primary'
                            : 'bg-[#050505] hover:bg-[#121212] border-white/5 text-white/50 hover:text-white'
                        }`}
                      >
                        {slot}
                      </button>
                    );
                  })}
                </div>
              </div>

              <div className="pt-4 flex justify-between">
                <button
                  onClick={handlePrevStep}
                  className="flex items-center gap-2 px-5 py-3 border border-white/5 hover:bg-[#121212] rounded-none font-mono text-xs uppercase tracking-widest text-white/50 hover:text-white transition-all"
                >
                  <ChevronLeft className="w-4 h-4" /> Back
                </button>
                <button
                  onClick={handleNextStep}
                  disabled={!selectedDate || !selectedTime}
                  className={`flex items-center gap-2 px-6 py-3 rounded-none font-mono text-xs uppercase tracking-widest font-bold transition-all ${
                    selectedDate && selectedTime
                      ? 'bg-primary text-on-primary hover:opacity-95'
                      : 'bg-white/5 text-white/30 cursor-not-allowed'
                  }`}
                >
                  Add Details <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </motion.div>
          )}

          {step === 4 && (
            <motion.div
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 10 }}
            >
              <form onSubmit={handleBookingSubmit} className="space-y-4">
                <div>
                  <label htmlFor={nameInputId} className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-2">
                    Your Name *
                  </label>
                  <input
                    id={nameInputId}
                    type="text"
                    required
                    placeholder="Enter your full name"
                    value={clientName}
                    onChange={(e) => setClientName(e.target.value)}
                    className="w-full bg-[#050505] border border-white/10 rounded-none px-4 py-3 text-sm text-white placeholder-white/30 focus:outline-none focus:border-primary transition-colors focus:ring-1 focus:ring-primary"
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label htmlFor={phoneInputId} className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-2">
                      Phone Number *
                    </label>
                    <input
                      id={phoneInputId}
                      type="tel"
                      required
                      placeholder="e.g., 62807-41173"
                      value={clientPhone}
                      onChange={(e) => setClientPhone(e.target.value)}
                      className="w-full bg-[#050505] border border-white/10 rounded-none px-4 py-3 text-sm text-white placeholder-white/30 focus:outline-none focus:border-primary transition-colors focus:ring-1 focus:ring-primary"
                    />
                  </div>
                  <div>
                    <label htmlFor={emailInputId} className="block text-xs font-mono uppercase tracking-widest text-white/50 mb-2">
                      Email Address (Optional)
                    </label>
                    <input
                      id={emailInputId}
                      type="email"
                      placeholder="e.g., mail@example.com"
                      value={clientEmail}
                      onChange={(e) => setClientEmail(e.target.value)}
                      className="w-full bg-[#050505] border border-white/10 rounded-none px-4 py-3 text-sm text-white placeholder-white/30 focus:outline-none focus:border-primary transition-colors focus:ring-1 focus:ring-primary"
                    />
                  </div>
                </div>

                <div className="p-4 bg-primary/5 rounded-none border border-primary/20 flex gap-3 mt-6">
                  <ShieldCheck className="w-5 h-5 text-primary shrink-0" />
                  <p className="text-xs text-white/50 leading-relaxed font-light">
                    By submitting, your appointment is logged locally. We recommend arriving 10 minutes prior to your styling slot at S.B.P City Center, Mohali.
                  </p>
                </div>

                {error && (
                  <div className="p-4 bg-red-500/10 rounded-none border border-red-500/20 flex gap-3 mt-6">
                    <p className="text-xs text-red-400 leading-relaxed font-light">
                      {error}
                    </p>
                  </div>
                )}

                <div className="pt-6 flex justify-between border-t border-white/5 mt-6">
                  <button
                    type="button"
                    onClick={handlePrevStep}
                    disabled={isLoading}
                    className="flex items-center gap-2 px-5 py-3 border border-white/5 hover:bg-[#121212] rounded-none font-mono text-xs uppercase tracking-widest text-white/50 hover:text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    <ChevronLeft className="w-4 h-4" /> Back
                  </button>
                  <button
                    type="submit"
                    disabled={!clientName || !clientPhone || isLoading}
                    className={`flex items-center gap-2 px-8 py-3 rounded-none font-mono text-xs uppercase tracking-widest font-bold transition-all ${
                      clientName && clientPhone && !isLoading
                        ? 'bg-primary text-on-primary hover:opacity-95'
                        : 'bg-white/5 text-white/30 cursor-not-allowed'
                    }`}
                  >
                    {isLoading ? (
                      <>
                        <span className="animate-spin">⏳</span> Confirming...
                      </>
                    ) : (
                      <>
                        Confirm Appointment <Sparkles className="w-4 h-4" />
                      </>
                    )}
                  </button>
                </div>
              </form>
            </motion.div>
          )}

          {step === 5 && successBooking && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="text-center py-8 space-y-6 animate-in fade-in zoom-in-95 duration-500"
            >
              <div className="w-20 h-20 bg-primary/20 text-primary rounded-none flex items-center justify-center mx-auto border border-primary/30">
                <Check className="w-10 h-10" />
              </div>

              <div className="space-y-2">
                <h4 className="font-display text-2xl uppercase tracking-wider text-primary font-light">Session Secured!</h4>
                <p className="text-sm text-white/50 font-sans font-light">Your appointment has been logged successfully</p>
                <p className="text-xs font-mono text-primary uppercase tracking-wider">ID: {successBooking.id}</p>
              </div>

              <div className="max-w-md mx-auto bg-[#050505] border border-white/5 p-6 rounded-none text-left divide-y divide-white/5 space-y-3">
                <div className="flex justify-between pb-2 text-xs">
                  <span className="text-white/40 uppercase font-mono">Service:</span>
                  <span className="text-white font-bold font-display uppercase tracking-wider">{successBooking.serviceName}</span>
                </div>
                <div className="flex justify-between py-2 text-xs">
                  <span className="text-white/40 uppercase font-mono">Stylist:</span>
                  <span className="text-white font-bold uppercase tracking-wider">{successBooking.stylistName}</span>
                </div>
                <div className="flex justify-between py-2 text-xs">
                  <span className="text-white/40 uppercase font-mono">Date:</span>
                  <span className="text-white font-mono font-bold">{successBooking.date}</span>
                </div>
                <div className="flex justify-between py-2 text-xs">
                  <span className="text-white/40 uppercase font-mono">Time:</span>
                  <span className="text-white font-mono font-bold">{successBooking.time}</span>
                </div>
                <div className="flex justify-between pt-2 text-xs">
                  <span className="text-white/40 uppercase font-mono">Client Name:</span>
                  <span className="text-white font-bold">{successBooking.clientName}</span>
                </div>
              </div>

              <div className="pt-6">
                <button
                  onClick={resetForm}
                  className="px-8 py-3 bg-primary text-on-primary rounded-none font-mono text-xs uppercase tracking-widest font-bold hover:opacity-95 transition-all"
                >
                  Book Another Session
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Booking Summary Column */}
      <div className="lg:col-span-4 space-y-6">
        <div className="bg-[#0d0d0d] border border-white/5 rounded-none p-6 studio-light">
          <h4 className="font-display text-sm uppercase tracking-widest text-primary border-b border-white/5 pb-3 mb-4 font-bold">
            Reservation Summary
          </h4>

          {selectedService || selectedStylist || (selectedDate && selectedTime) ? (
            <div className="space-y-4">
              {selectedService && (
                <div className="flex gap-3 items-start">
                  <Sparkles className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <div>
                    <p className="text-[10px] font-mono uppercase tracking-widest text-white/40">Chosen Service</p>
                    <p className="font-display text-xs uppercase tracking-wider text-white mt-1">{selectedService.name}</p>
                    <p className="text-xs font-mono font-bold text-primary mt-1">{selectedService.price}</p>
                  </div>
                </div>
              )}

              {selectedStylist && (
                <div className="flex gap-3 items-start border-t border-white/5 pt-3">
                  <User className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <div>
                    <p className="text-[10px] font-mono uppercase tracking-widest text-white/40">Elite Artist</p>
                    <p className="font-display text-xs uppercase tracking-wider text-white mt-1">{selectedStylist.name}</p>
                    <p className="text-xs font-mono text-primary/70 uppercase mt-0.5">{selectedStylist.role}</p>
                  </div>
                </div>
              )}

              {selectedDate && selectedTime && (
                <div className="flex gap-3 items-start border-t border-white/5 pt-3">
                  <Calendar className="w-4 h-4 text-primary shrink-0 mt-1" />
                  <div>
                    <p className="text-[10px] font-mono uppercase tracking-widest text-white/40">Date &amp; Slot</p>
                    <p className="font-mono text-xs text-white mt-1">{selectedDate} at {selectedTime}</p>
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-8 text-white/30 space-y-2">
              <Calendar className="w-8 h-8 mx-auto stroke-1" />
              <p className="text-xs font-mono uppercase tracking-wider">No Reservation Details</p>
              <p className="text-[10px] font-sans font-light">Begin your reservation by selecting an elite service catalog.</p>
            </div>
          )}
        </div>

        {/* Existing Bookings Dashboard */}
        <div className="bg-[#0d0d0d] border border-white/5 rounded-none p-6 studio-light">
          <div className="flex justify-between items-center border-b border-white/5 pb-3 mb-4">
            <h4 className="font-display text-sm uppercase tracking-widest text-white">
              Your Appointments
            </h4>
            <span className="text-xs font-mono bg-white/5 text-white/80 px-2 py-0.5 rounded-none border border-white/10">
              {existingBookings.length}
            </span>
          </div>

          {existingBookings.length > 0 ? (
            <div className="space-y-3 max-h-[320px] overflow-y-auto pr-1">
              {existingBookings.map((booking) => (
                <div
                  key={booking.id}
                  className="bg-[#050505] border border-white/5 p-3 rounded-none flex justify-between items-start group"
                >
                  <div className="space-y-1">
                    <p className="font-display text-xs uppercase tracking-wider text-white line-clamp-1">
                      {booking.serviceName}
                    </p>
                    <p className="text-[10px] text-white/50">
                      Artist: <span className="text-white">{booking.stylistName}</span>
                    </p>
                    <div className="flex items-center gap-2 text-[10px] font-mono text-primary mt-1">
                      <Clock className="w-3 h-3" />
                      <span>{booking.date} @ {booking.time}</span>
                    </div>
                  </div>
                  <button
                    onClick={() => onCancelBooking(booking.id)}
                    className="text-white/40 hover:text-red-400 p-1 hover:bg-red-400/10 rounded-none transition-colors"
                    title="Cancel Appointment"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-6 text-white/30 space-y-2">
              <Clock className="w-6 h-6 mx-auto stroke-1" />
              <p className="text-[10px] font-mono uppercase tracking-wider">No active appointments logged</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
